config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  get 'dashboard', to: 'dashboard#index'

  resources :products, only: %i[index new show edit create update] do
    resources :contents, only: :index, controller: 'products/contents'
    resources :attach_contents, only: :create, controller: 'products/attach_contents'
  end

  scope module: :products, path: :products, as: :product do
    resources :publish, only: :update
    resources :unpublish, only: :update
  end

  namespace :api do
    resources :contents, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :product, optional: true

  validates :name, presence: true

  has_one_attached :file
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  monetize :price_cents, allow_nil: true
  belongs_to :user
  has_many :contents, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :user_id }

  has_rich_text :description

  has_one_attached :thumbnail

  has_one_attached :cover

  def draft?
    !published?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
end

app/controllers/api/contents_controller.rb
module Api
  class ContentsController < ApplicationController
    protect_from_forgery with: :null_session
    # before_action :authenticate_user!

    def create
      @content = Content.create(content_params)

      respond_to do |format|
        format.turbo_stream
      end
    end

    def update
      @content = Content.find(params[:id])
      @content.file.attach(content_params[:file])
      respond_to do |format|
        format.json do
          render json: {}, status: 200
        end
      end
    end

    def destroy
      @content = Content.find(params[:id])
      @content.destroy
      respond_to do |format|
        format.json do
          render json: {}, status: 200
        end
      end
    end

    private

    def content_params
      params.require(:content).permit(:name, :file_type, :file_size, :file)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    flash.now[:notice] = {
      title: 'Successfully Sign Up',
      body: 'Welcome to our application'
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/products/attach_contents_controller.rb
module Products
  class AttachContentsController < ApplicationController
    protect_from_forgery with: :null_session
    # before_action :authenticate_user!

    def create
      @product = Product.friendly.find(params[:product_id])
      @contents = []

      content_params[:contents].each do |content_param|
        content = Content.find(content_param[:id])
        content.name = content_param[:name]
        content.description = content_param[:description].blank? ? nil : content_param[:description]
        content.product_id = @product.id
        @contents << content
      end
      @contents.each(&:save)
      respond_to do |format|
        format.turbo_stream do
          flash[:success] = 'Files successfully uploaded'
        end
      end
    end

    def destroy
      @product = Product.friendly.find(params[:product_id])
    end

    private

    def content_params
      params.permit(contents: %i[id name description])
    end
  end
end

app/controllers/products/contents_controller.rb
module Products
  class ContentsController < ApplicationController
    before_action :authenticate_user!

    def index
      @product = Product.friendly.find(params[:product_id])
      @contents = @product.contents
    end
  end
end

app/controllers/products/publish_controller.rb
# frozen_string_literal :true
module Products
  class PublishController < ApplicationController
    before_action :authenticate_user!
    def update
      @product = Product.friendly.find(params[:id])
      @product.update(published: true)
      respond_to do |format|
        format.turbo_stream do
          flash.now[:success] = 'Product successfully published.'
          render turbo_stream: [
            turbo_stream.update('publish-button', partial: 'products/publish_button', locals: { product: @product.reload }),
            turbo_stream.update('flash', partial: 'layouts/flash')
          ]
        end
      end
    end
  end
end

app/controllers/products/unpublish_controller.rb
module Products
  class UnpublishController < ApplicationController
    before_action :authenticate_user!
    def update
      @product = Product.friendly.find(params[:id])
      @product.update(published: false)
      respond_to do |format|
        format.turbo_stream do
          flash.now[:success] = 'Product successfully unpublished'
          render turbo_stream: [
            turbo_stream.update('publish-button', partial: 'products/publish_button',
                                                  locals: { product: @product.reload }),
            turbo_stream.update('flash', partial: 'layouts/flash')
          ]
        end
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def new
    @product = current_user.products.build
  end

  def edit
    @product = Product.friendly.find(params[:id])
  end

  def create
    @product = Product.new(product_params.merge(user: current_user))

    if @product.save
      redirect_to edit_product_path(@product)
    else
      # Error
    end
  end

  def show
    @product = Product.friendly.find(params[:id])
  end

  def update
    @product = Product.friendly.find(params[:id])

    if @product.update(product_params)
      flash[:success] = 'Product successfully updated.'
      redirect_to edit_product_path(@product)
    else
      # Error
    end
  end

  private

  def product_params
    params[:product].delete(:price) if params[:product][:price].to_f.zero?
    params.require(:product).permit(:name, :description, :thumbnail, :cover, :price, :slug, contents: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def horizontal_padding
    "px-4 sm:px-6 lg:px-8"
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def active_tab_class
    "rounded-full bg-indigo-600 px-3.5 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
  end

  def inactive_tab_class
    "rounded-full bg-white px-3.5 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
  end
end

app/helpers/sidenav_helper.rb
module SidenavHelper
  def link_active?(link_name)
    if controller_name == link_name
      'bg-gray-50 text-indigo-600'
    else
      'text-gray-700 hover:text-indigo-600 hover:bg-gray-50'
    end
  end

  def svg_link_active?(link_name)
    if controller_name == link_name
      'text-indigo-600'
    else
      'text-gray-400 group-hover:text-indigo-600'
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_flash.html.erb
<% flash.each do |type, data| %>
  <%= render NotificationComponent.new(type: type, data: data) %>
<% end %>

app/views/layouts/_sidenav.html.erb
  <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
<div data-controller="sidenav">
  <div
      data-sidenav-target="nav"
      class="relative hidden z-50" 
      role="dialog" 
      aria-modal="true"   
      >
    <!--
      Off-canvas menu backdrop, show/hide based on off-canvas menu state.

      Entering: "transition-opacity ease-linear duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "transition-opacity ease-linear duration-300"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div 
        data-sidenav-target="backdrop"
        class="fixed inset-0 bg-gray-900/80"
        data-transition-enter="transition-opacity ease-linear duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="transition-opacity ease-linear duration-300"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
    ></div>

    <div class="fixed inset-0 flex">
      <!--
        Off-canvas menu, show/hide based on off-canvas menu state.

        Entering: "transition ease-in-out duration-300 transform"
          From: "-translate-x-full"
          To: "translate-x-0"
        Leaving: "transition ease-in-out duration-300 transform"
          From: "translate-x-0"
          To: "-translate-x-full"
      -->
      <div 
          data-sidenav-target="canvas"
          class="relative mr-16 flex w-full max-w-xs flex-1"
          data-transition-enter="transition ease-in-out duration-300 transform"
          data-transition-enter-start="-translate-x-full"
          data-transition-enter-end="translate-x-0"
          data-transition-leave="transition ease-in-out duration-300 transform"
          data-transition-leave-start="translate-x-0"
          data-transition-leave-end="-translate-x-full"
        >
        <!--
          Close button, show/hide based on off-canvas menu state.

          Entering: "ease-in-out duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "ease-in-out duration-300"
            From: "opacity-100"
            To: "opacity-0"
        -->
        <div 

          data-sidenav-target="closeButton"
          data-action="click->sidenav#closeSidenav"
          class="absolute left-full top-0 flex w-16 justify-center pt-5"
          data-transition-enter="ease-in-out duration-300"
          data-transition-enter-start="opacity-0"
          data-transition-enter-end="opacity-100"
          data-transition-leave="ease-in-out duration-300"
          data-transition-leave-start="opacity-100"
          data-transition-leave-end="opacity-0"
          >
          <button 
          type="button" 
          class="-m-2.5 p-2.5">
            <span class="sr-only">Close sidebar</span>
            <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Sidebar component, swap this element with another sidebar if you like -->
        <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-white px-6 pb-2">
          <div class="flex h-16 shrink-0 items-center">
            <%= image_tag "buymeabugatti-nobg.png", class: "h-12 w-auto", "alt": "Buy me a Bugatti" %>
          </div>
          <nav class="flex flex-1 flex-col">
            <ul role="list" class="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" class="-mx-2 space-y-1">
                  <li>
                    <!-- Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" -->
                    <%= link_to dashboard_path, class: "#{link_active?("dashboard")} group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6" do %>
                      <svg class="<%= svg_link_active?("dashboard") %> h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                      </svg>
                      Dashboard
                    <% end %>
                      
                  </li>
                  <li>
                    <%= link_to products_path, class: "#{link_active?("products")} group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6" do %>
                      <svg class="<%= svg_link_active?("products") %> h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
                      </svg>
                      Products
                    <% end %>
                  </li>
                </ul>
              </li>
              <li>
                <div class="text-xs font-semibold leading-6 text-gray-400">Your teams</div>
                <ul role="list" class="-mx-2 mt-2 space-y-1">
                  <li>
                    <!-- Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" -->
                    <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
                      <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-[0.625rem] font-medium text-gray-400 group-hover:border-indigo-600 group-hover:text-indigo-600">H</span>
                      <span class="truncate">Heroicons</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
                      <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-[0.625rem] font-medium text-gray-400 group-hover:border-indigo-600 group-hover:text-indigo-600">T</span>
                      <span class="truncate">Tailwind Labs</span>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
                      <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-[0.625rem] font-medium text-gray-400 group-hover:border-indigo-600 group-hover:text-indigo-600">W</span>
                      <span class="truncate">Workcation</span>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  <!-- Static sidebar for desktop -->
  <div class="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
    <!-- Sidebar component, swap this element with another sidebar if you like -->
    <div class="flex grow flex-col gap-y-5 overflow-y-auto border-r border-gray-200 bg-white px-6">
      <div class="flex h-16 shrink-0 items-center">
        <%= image_tag "buymeabugatti-nobg.png", class: "h-12 w-auto", "alt": "Buy me a Bugatti" %>
      </div>
      <nav class="flex flex-1 flex-col">
        <ul role="list" class="flex flex-1 flex-col gap-y-7">
          <li>
            <ul role="list" class="-mx-2 space-y-1">
              <li>
                <!-- Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" -->
                <%= link_to dashboard_path, class: "#{link_active?("dashboard")} group flex gap-x-3 rounded-md  p-2 text-sm font-semibold leading-6" do %>
                  <svg class="<%= svg_link_active?("dashboard") %> h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                  </svg>
                  Dashboard
                <% end %>
              </li>
              <li>
                <%= link_to products_path, class: "#{link_active?("products")} group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6" do %>
                  <svg class="<%= svg_link_active?("products") %> h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
                  </svg>
                  Products
                <% end %>
              </li>
            </ul>
          </li>
          <li class="-mx-6 mt-auto">
            <a href="#" class="flex items-center gap-x-4 px-6 py-3 text-sm font-semibold leading-6 text-gray-900 hover:bg-gray-50">
              <img class="h-8 w-8 rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              <span class="sr-only">Your profile</span>
              <span aria-hidden="true">Tom Cook</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="sticky top-0 z-40 flex items-center gap-x-6 bg-white px-4 py-4 shadow-sm sm:px-6 lg:hidden">
    <button 
       data-sidenav-target="openButton"
       data-action="click->sidenav#openSidenav"
       type="button" 
       class="-m-2.5 p-2.5 text-gray-700 lg:hidden">
      <span class="sr-only">Open sidebar</span>
      <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
      </svg>
    </button>
    <div class="flex-1 text-sm font-semibold leading-6 text-gray-900">Dashboard</div>
    <a href="#">
      <span class="sr-only">Your profile</span>
      <img class="h-8 w-8 rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
    </a>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= "h-full bg-gray-50" if devise_controller? || user_signed_in? %>">
  <head>
    <title>Buymeabugatti</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= favicon_link_tag asset_path('buymeabugatti-nobg.png') %>
     
  </head>

  <body class="<%= "h-full" if devise_controller? || user_signed_in? %>">
    <% if user_signed_in? %>
      <%# This a temporary solutioc%>
      <% if controller_name == "products" && action_name == "show" %>
        <%= yield %>
      <% else %>
        <div>
          <%= render "layouts/sidenav" %>
          <main class="py-10 lg:pl-72">
            <!-- Your content -->
            <%= yield %>
          </main>
        </div>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
    <!-- Global notification live region, render this permanently at the end of the document -->
    <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6 z-50">
      <%= turbo_frame_tag "flash", class: "flex w-full flex-col items-center space-y-4 sm:items-end" do %>
        <%= render "layouts/flash" %>
      <% end %>
    </div>
  </body>
</html>

app/views/products/_publish_button.html.erb
<% if product.published? %>
  <%= link_to "Unpublish", product_unpublish_path(product), class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50", data: { "turbo-method": :put } %>
<% else %>
  <%= link_to "Publish", product_publish_path(product), class: "rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50", data: { "turbo-method": :put} %>
<% end %>

app/views/products/_sticky_header.html.erb
  <div class="sticky z-50 top-0 bg-gray-50 py-12 border-b border-black <%= horizontal_padding %>">
    <div class="flex justify-between">
      <div class="text-4xl tracking-wide"><%= product.name %></div>
      <div>
        <%= turbo_frame_tag "publish-button" do %>
          <%= render "products/publish_button", product: product %>
        <% end %>
        <%= form.submit "Save Changes", class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"  %>
      </div>
    </div>

    <div class="flex justify-start mt-10">
      <div class=""><%= link_to "Product", edit_product_path(product), class: controller_name == "products" ? active_tab_class : inactive_tab_class %></div>
      <div class="ml-4"><%= link_to "Content", product_contents_path(product), class: controller_name == "contents" ? active_tab_class : inactive_tab_class %></div>
    </div>
  </div>

app/views/products/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Products</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to "Add Product", new_product_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full table-auto divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                <span class=="sr-only">Thumbnail</span>
              </th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Price</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% @products.each do |product| %>
              <tr>
                <td class="whitespace-nowrap py-5 px-3 text-sm text-gray-500 mx-auto sm:pl-0 w-0">
                  <div class="h-11 w-11 flex-shrink-0">
                    <% if product.thumbnail.attached? %>
                      <%= image_tag product.thumbnail.variant(resize_to_fill: [500, 500]) %>
                    <% else %>
                      <%= image_tag "gallery.png" %>
                    <% end %>
                  </div>
                </td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                  <div class="font-medium text-gray-900"><%= product.name %></div>
                  <div class="mt-1 text-gray-500"><%= product_url(product) %></div>
                </td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= humanized_money_with_symbol(product.price) %></td>
                <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= product.published? ? "Published" : "Unpublished" %></td>
                <td class="relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <%= link_to "Edit", edit_product_path(product), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>

            <% end %>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="mx-auto container <%= horizontal_padding %>">
  <%= image_tag @product.cover, class: "block" %>
  <div class="grid grid-cols-3">
    <div class="col-span-2">
      <h1 class="text-4xl tracking-wide"><%= @product.name %></h1>
      <p><%= humanized_money_with_symbol(@product.price) %> | <%= @product.user.email %></p>
      <div>
        <%= @product.description %>
      </div>
    </div>
    <div class="col-span-1">
      <%= button_tag "I want this!" %>
      <%= number_to_human_size(@product.contents.pluck(:file_size).sum) %>
    </div>
  </div>
</div>